FROM golang:1.21 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o dashlytics-backend ./cmd/server/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/dashlytics-backend .
COPY ./docs ./docs

EXPOSE 8080

CMD ["./dashlytics-backend"]
