version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dashlytics-backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./dashlytics-frontend
      dockerfile: Dockerfile.frontend
    container_name: dashlytics-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
